{
  "hash": "a4864f796460714bdb1512401c50b5fe",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Electronics and Circuits\"\n---\n\n## Overview {#sec-electronics-overview}\n\nThis section consolidates all circuit designs for the HIRT system, including the MIT (Magneto-Inductive Tomography) circuits, ERT (Electrical Resistivity Tomography) circuits, and base hub electronics. The design uses **centralized electronics with passive probes**: all active components reside in the surface hub, while probes contain only coils and electrodes.\n\nThis architecture offers significant advantages: lower per-probe cost, easier maintenance, better reliability (passive probes are more robust), centralized firmware updates, and simplified probe construction. The trade-off is increased cabling complexity for the multi-probe harness.\n\n::: {.callout-tip}\n## Hardware Documentation Reference\n\nComplete circuit schematics and detailed design notes are maintained in the hardware documentation:\n\n- **MIT Circuit:** `/hardware/schematics/electronics/mit-circuit.md` - Full TX/RX chain design with component values\n- **ERT Circuit:** `/hardware/schematics/electronics/ert-circuit.md` - Howland current source and measurement circuits\n- **Base Hub Circuit:** `/hardware/schematics/electronics/base-hub-circuit.md` - Central hub electronics integration\n- **Block Diagrams:** `/hardware/schematics/electronics/probe-electronics-block.md` - System-level block diagrams\n\nThe diagrams in this section provide conceptual overviews; refer to the hardware schematics for exact component values and PCB layout guidance.\n:::\n\n## System Block Diagram {#sec-system-block}\n\n::: {#cell-fig-system-block-elec .cell fig-height='7' fig-width='11' execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![Complete HIRT system architecture showing the central electronics hub, zone wiring strategy, and passive probe connections. All signal processing occurs in the hub; probes are purely passive sensors.](electronics_files/figure-html/fig-system-block-elec-output-1.png){#fig-system-block-elec}\n:::\n:::\n\n\nThe central hub contains: (1) MCU for control and DSP, (2) MIT transmitter chain (DDS + power driver), (3) MIT receiver chain (preamp + instrumentation amplifier + ADC), (4) ERT current source and voltage measurement, and (5) high-density analog multiplexers. These connect via DB25 trunk cables to passive **Zone Hubs**, which then distribute signals to individual probes.\n\n## MIT Transmit (TX) Chain {#sec-mit-tx}\n\n::: {#cell-fig-mit-tx-chain .cell fig-height='4' fig-width='10' execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![MIT transmitter signal chain from MCU through DDS, filtering, and power driver to the TX coil. Operating frequency range is 2-50 kHz.](electronics_files/figure-html/fig-mit-tx-chain-output-1.png){#fig-mit-tx-chain}\n:::\n:::\n\n\n## DDS Sine Generator {#sec-dds}\n\nThe transmit chain begins with a Direct Digital Synthesis (DDS) generator, the **AD9833**. This IC provides a highly precise sine wave output from 0.1 Hz to 12.5 MHz with 28-bit frequency resolution. Its compact MSOP-10 footprint and low power consumption make it ideal for the 2-50 kHz HIRT operating range.\n\n| Parameter | Specification |\n|-----------|---------------|\n| Part Number | **AD9833BRMZ** |\n| Frequency Range | 0 Hz to 12.5 MHz |\n| Output Level | 0.6 V p-p sine wave |\n| Interface | SPI (3-wire) |\n| Resolution | 28-bit frequency, 12-bit phase |\n| Power Supply | 2.3-5.5V, 12.65 mW typical |\n\n: AD9833 DDS Generator Specifications. {#tbl-dds-specs}\n\n## TX Power Driver {#sec-tx-driver}\n\nThe DDS output is buffered by a **Texas Instruments OPA2186** precision operational amplifier. This component is selected for its zero-drift architecture and ultra-low quiescent current (**90 µA** **(Modeled)**), which ensures high precision and extended battery life for the hub while maintaining rail-to-rail output for the TX coil drive.\n\n| Parameter | OPA2186 Specification |\n|-----------|------------------|\n| Quiescent Current | **90 µA** |\n| Drift | **0.04 µV/°C** (Zero-Drift) |\n| Offset Voltage | 10 µV |\n| Power Supply | 4.5V to 36V |\n\n: TX Driver Op-Amp Specifications. {#tbl-tx-driver}\n\n## MIT Receive (RX) Chain {#sec-mit-rx}\n\n::: {#cell-fig-mit-rx-chain .cell fig-height='4' fig-width='10' execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![MIT receiver signal chain. The updated 2026 architecture uses the AD8421 for ultra-low noise preamplification (3 nV/rtHz), followed by the integrated AD7124-8 AFE.](electronics_files/figure-html/fig-mit-rx-chain-output-1.png){#fig-mit-rx-chain}\n:::\n:::\n\n\n## RX Preamplifier (AD8421) {#sec-rx-preamp}\n\nThe receiver front-end utilizes the **Analog Devices AD8421**. This high-speed instrumentation amplifier features an exceptionally low input voltage noise floor of **3 nV/$\\sqrt{\\mathrm{Hz}}$** **(Modeled)**. This performance characteristic is essential for resolving the weak secondary magnetic fields generated by subsurface targets in the MIT tomography process.\n\n| Parameter | Specification |\n|-----------|---------------|\n| Component | **AD8421** |\n| Input Noise | **3 nV/$\\sqrt{\\mathrm{Hz}}$** **(Modeled)** |\n| Bandwidth (G=10) | 10 MHz |\n| Slew Rate | 35 V/µs |\n| Supply Current | 2.0 mA |\n\n: RX Preamplifier Specifications. {#tbl-preamp-specs}\n\n### Zero-Drift Alternative: INA188 {#sec-ina188-alternative}\n\nFor applications prioritizing DC stability over AC noise floor, the **Texas Instruments INA188** provides a zero-drift alternative to the AD8421.\n\n| Parameter | AD8421 | INA188 | Trade-off |\n|-----------|--------|--------|-----------|\n| Noise Floor | **3 nV/$\\sqrt{\\mathrm{Hz}}$** | 12 nV/$\\sqrt{\\mathrm{Hz}}$ | AD8421 superior for AC |\n| Offset Drift | 0.6 µV/°C | **0.2 µV/°C** | INA188 superior for DC |\n| 1/f Noise | Present | **Eliminated** | INA188 better at DC |\n| Supply Current | 2.0 mA | 1.4 mA | Similar |\n\n: AD8421 vs INA188 comparison. {#tbl-preamp-comparison}\n\n**Recommendation:** For HIRT's MIT operating range (2-50 kHz), the AD8421's ultra-low broadband noise provides better SNR than the INA188's zero-drift architecture. Use the INA188 only if your application requires DC-accurate measurements or operates below 100 Hz.\n\n### Noise Floor Measurement Conditions {#sec-noise-conditions}\n\nThe AD8421's specified noise floor of **3 nV/$\\sqrt{\\mathrm{Hz}}$** is achieved under specific measurement conditions. Field performance depends on several factors:\n\n| Condition | Specification | Field Typical | Impact on SNR |\n|-----------|---------------|---------------|---------------|\n| Bandwidth | 1-50 kHz (HIRT operating range) | 2-50 kHz | ~100 nV RMS integrated |\n| Temperature | 25°C reference | -10 to +40°C | ±10% variation |\n| Cable length | <1 m bench test | 3-5 m probe cable | +20-50% noise pickup |\n| Averaging | 100-sample mean | 16-64 samples typical | Improves by $\\sqrt{N}$ |\n\n: Noise floor measurement conditions and field impact. {#tbl-noise-conditions}\n\n**Integrated Noise Calculation:** For a 1-50 kHz bandwidth (49 kHz span), the theoretical integrated input-referred noise is:\n\n$$V_{n,rms} = 3\\ \\text{nV}/\\sqrt{\\text{Hz}} \\times \\sqrt{49,000\\ \\text{Hz}} \\approx 100\\ \\text{nV RMS}$$\n\nThis represents the *design target* under controlled conditions. Field measurements typically show 150-300 nV RMS due to cable capacitance, EMI pickup, and connector losses.\n\n::: {.callout-note}\n## Performance Claim Context\n\nThe ~100 nV noise floor is a **design target** based on component specifications and bench measurements. Actual field performance varies with environmental conditions and cable routing. For planning purposes, assume 200-300 nV RMS input-referred noise in typical outdoor conditions.\n:::\n\n## Signal Conditioning and Gain Stage {#sec-signal-conditioning}\n\nFollowing the AD8421 preamplifier, the signal passes through additional gain and filtering stages before reaching the ADC. An instrumentation amplifier (INA128) provides adjustable gain to match signal levels to the ADC input range. The total signal chain gain is typically 800-1000x, bringing microvolt-level coil signals up to the millivolt range required by the ADC.\n\n## Signal Level Progression {#sec-signal-levels}\n\n::: {#cell-fig-signal-level .cell fig-height='5' fig-width='10' execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![Signal level progression through the MIT RX chain. The signal starts at approximately 1 uV at the coil and is amplified to 0.8 mV at the ADC input. The noise floor also rises but at a slower rate, maintaining adequate SNR.](electronics_files/figure-html/fig-signal-level-output-1.png){#fig-signal-level}\n:::\n:::\n\n\n## Lock-In Detection {#sec-lockin}\n\nLock-in detection is essential for extracting weak MIT signals from noise. The HIRT system uses **digital lock-in detection** implemented in the MCU, which offers flexibility, software configurability, and no analog drift. The technique multiplies the received signal by reference sine and cosine waveforms at the excitation frequency, then low-pass filters to extract the in-phase (I) and quadrature (Q) components.\n\n::: {#cell-fig-lockin-detection .cell fig-height='5' fig-width='10' execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![Digital lock-in detection block diagram. The RX signal is multiplied by reference sine (Q-channel) and cosine (I-channel) signals, then filtered and integrated. Amplitude A = sqrt(I^2 + Q^2) and phase Phi = atan2(Q,I) are computed from the I/Q outputs.](electronics_files/figure-html/fig-lockin-detection-output-1.png){#fig-lockin-detection}\n:::\n:::\n\n\nThe lock-in algorithm provides exceptional noise rejection (> 40 dB improvement) by responding only to signals at the exact reference frequency. This allows detection of MIT signals buried deep in noise, critical for weak responses from distant or low-conductivity targets.\n\n## Digital Lock-In Algorithm {#sec-lockin-algorithm}\n\n```c\n// Simplified digital lock-in implementation\nfloat I_sum = 0, Q_sum = 0;\nfor (int i = 0; i < N_samples; i++) {\n    float sample = read_adc();\n    float ref_I = sin(2 * PI * f * i / Fs);\n    float ref_Q = cos(2 * PI * f * i / Fs);\n    I_sum += sample * ref_I;\n    Q_sum += sample * ref_Q;\n}\nfloat amplitude = sqrt(I_sum*I_sum + Q_sum*Q_sum) / N_samples;\nfloat phase = atan2(Q_sum, I_sum);\n```\n\n## ERT Current Source (Howland Pump) {#sec-ert-current}\n\nThe ERT subsystem injects controlled current into the ground through electrode rings and measures the resulting voltage distribution. The current source uses a **Howland current pump** topology, which provides high output impedance (>1 M-ohm) and stable current regardless of load variations.\n\n::: {#cell-fig-ert-current-source .cell fig-height='6' fig-width='10' execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Howland current pump circuit for ERT measurements. When R1=R2=R3=R4, the output current is I_out = V_in / R_sense, independent of load impedance. A precision 2.5V reference (REF5025) provides stable input voltage.](electronics_files/figure-html/fig-ert-current-source-output-1.png){#fig-ert-current-source}\n:::\n:::\n\n\n| Parameter | Specification |\n|-----------|---------------|\n| Output Current | 0.5-2 mA (adjustable) |\n| Current Accuracy | +/- 5% |\n| Compliance Voltage | +/- 10V minimum |\n| Output Impedance | > 1 M-ohm |\n| Load Range | 100 ohm - 10 k-ohm |\n| Polarity Reversal | Programmable (0.5 Hz) |\n\n: ERT Current Source Specifications. {#tbl-ert-current}\n\n### Compliance Voltage vs Load {#sec-ert-compliance}\n\nThe +/-10V compliance voltage determines the maximum load impedance at each current setting. Operators should select current levels based on expected soil resistivity to ensure adequate measurement headroom:\n\n| Max Current | Max Load at 10V | Typical Application |\n|-------------|-----------------|---------------------|\n| 2.0 mA | 5 k-ohm | Low resistivity soil (<100 ohm-m) |\n| 1.0 mA | 10 k-ohm | Medium resistivity (100-500 ohm-m) |\n| 0.5 mA | 20 k-ohm | High resistivity (>500 ohm-m) |\n\n: ERT current vs load compliance limits. Higher resistivity soils require lower current to stay within compliance voltage. {#tbl-ert-compliance}\n\n::: {.callout-warning}\n## Compliance Limit Warning\n\nIf the load impedance exceeds the compliance limit for the selected current, the current source will saturate and actual injected current will be less than commanded. The ERT firmware monitors this condition and flags affected measurements. Reduce current setting or improve electrode contact if compliance warnings occur frequently.\n:::\n\n## Polarity Reversal {#sec-polarity-reversal}\n\nElectrode polarization causes measurement drift in DC systems. To mitigate this, HIRT reverses the current polarity every 2 seconds using a DPDT relay (G5V-2-H1) or solid-state switch (ADG1219). Positive and negative measurements are averaged to cancel polarization effects.\n\n::: {#cell-fig-polarity-reversal .cell fig-height='5' fig-width='8' execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![ERT polarity reversal circuit using a DPDT relay. The relay alternates current direction between Ring A and Ring B every 2 seconds, eliminating electrode polarization artifacts from the measurement.](electronics_files/figure-html/fig-polarity-reversal-output-1.png){#fig-polarity-reversal}\n:::\n:::\n\n\n## ADC Interface {#sec-adc}\n\n::: {#cell-fig-adc-interface .cell fig-height='5' fig-width='9' execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![AD7124-8 ADC interface showing differential analog inputs for MIT and ERT signals, SPI connection to MCU, and integrated reference. The integrated AFE, 24-bit resolution, and three power modes provide excellent dynamic range with minimal external components.](electronics_files/figure-html/fig-adc-interface-output-1.png){#fig-adc-interface}\n:::\n:::\n\n\nThe HIRT Rev B design uses the **Analog Devices AD7124-8** as the primary ADC. This integrated Analog Front End (AFE) dramatically reduces external component count compared to the legacy ADS1256, while providing superior power management for field deployment.\n\n| Parameter | AD7124-8 Specification |\n|-----------|----------------------|\n| Resolution | 24 bits |\n| Sample Rate | Up to 19.2 kSPS |\n| Noise | 24 nV RMS (at low output rates) |\n| Interface | SPI |\n| Integrated Features | Rail-to-rail buffer, PGA (1-128x), reference buffers |\n| Power Modes | Full (970 µA), Mid (660 µA), **Low (255 µA)** **(Modeled)** |\n| Input Channels | 8 differential or 15 single-ended |\n\n: AD7124-8 ADC Specifications (Rev B Primary). {#tbl-adc-specs}\n\n**Migration Note (Rev A to Rev B):** The AD7124-8 replaces the ADS1256 as the recommended ADC. Key advantages:\n\n- **Integrated AFE:** Internal rail-to-rail buffer and reference buffers eliminate ~6 external components\n- **Power efficiency:** Low-power mode (~255 µA) vs ADS1256 (~36 mW) enables significantly longer battery life\n- **Comparable noise:** 24 nV RMS achievable with fewer external noise sources\n\nThe ADS1256 remains documented for legacy builds (see [Legacy Components](#sec-legacy-components)).\n\n## Multiplexer Switching {#sec-multiplexer}\n\nWith up to 24 probes in a typical array, the HIRT system requires a scalable multiplexing strategy. The design uses **CD74HC4067** 16:1 analog multiplexers controlled by MCU GPIO pins. Each TX and RX signal path has its own multiplexer, allowing independent selection of transmit and receive probes. For arrays exceeding 16 probes, cascaded multiplexers can be used.\n\n::: {#cell-fig-mux-switching .cell fig-height='6' fig-width='10' execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![Multiplexer switching topology for probe selection. Separate TX and RX multiplexers allow any TX-RX probe combination to be measured. MCU GPIO controls multiplexer address lines (A0-A2).](electronics_files/figure-html/fig-mux-switching-output-1.png){#fig-mux-switching}\n:::\n:::\n\n\n## Power Distribution {#sec-power}\n\n::: {#cell-fig-power-distribution .cell fig-height='5' fig-width='10' execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Power distribution from 12V battery through regulators to various subsystems. Total system current is approximately 200 mA, providing several hours of operation from a 3S LiPo battery.](electronics_files/figure-html/fig-power-distribution-output-1.png){#fig-power-distribution}\n:::\n:::\n\n\n| Rail | Voltage | Current | Purpose |\n|------|---------|---------|---------|\n| +12V (Battery) | 11.1-12.6V | 200 mA total | System input |\n| +5V (LDO) | 5.0V | 50 mA | Power driver, references |\n| +3.3V (LDO) | 3.3V | 100 mA | MCU, ADC, digital |\n| -5V (Charge pump) | -5.0V | 10 mA | Op-amp negative rail |\n\n: Power Rail Specifications. {#tbl-power-rails}\n\n## Noise Filtering Stages {#sec-noise-filtering}\n\n::: {#cell-fig-noise-filtering .cell fig-height='4' fig-width='10' execution_count=11}\n\n::: {.cell-output .cell-output-display}\n![Cascaded noise filtering stages in the signal chain. Each stage targets specific noise sources: EMI, DC offsets, wideband noise, aliasing, and quantization noise. Combined rejection exceeds 60 dB.](electronics_files/figure-html/fig-noise-filtering-output-1.png){#fig-noise-filtering}\n:::\n:::\n\n\nNoise reduction is critical for MIT measurements where signal levels can be in the microvolt range. The filtering strategy employs multiple stages:\n\n- **Input RC filter (fc=100kHz):** Blocks RF interference and high-frequency EMI\n- **High-pass filter (fc=100Hz):** Removes DC offsets and 60Hz pickup\n- **Active band-pass (1-50kHz):** Passes only the measurement band\n- **Anti-aliasing filter (fc=15kHz):** Prevents aliasing in ADC sampling\n- **Digital matched filter:** Optimizes SNR in post-processing\n\n## Shielding and Ground Loop Prevention {#sec-grounding}\n\n::: {#cell-fig-ground-loop .cell fig-height='5' fig-width='10' execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![Ground loop prevention techniques. (a) shows the problem: multiple ground paths create loops that pick up EMI. (b) shows the solution: star grounding with a single connection point eliminates loops.](electronics_files/figure-html/fig-ground-loop-output-1.png){#fig-ground-loop}\n:::\n:::\n\n\nProper grounding is essential for achieving low-noise measurements. The HIRT design follows these best practices:\n\n- **Star grounding:** All ground returns connect at a single point near the ADC\n- **Separate ground planes:** Analog and digital grounds are split on the PCB\n- **Shielded cables:** All signal cables use twisted-pair with overall shield\n- **Single-point shield termination:** Shields grounded at hub end only\n- **Minimum loop area:** Signal and return paths routed together\n\n## PCB Layout Guidelines {#sec-pcb-layout}\n\n::: {#cell-fig-pcb-layout .cell fig-height='6' fig-width='10' execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![Recommended PCB layout showing component placement zones. The analog section (shielded) is physically separated from digital circuits. Ground plane spans the bottom layer with analog/digital split connected at a star point.](electronics_files/figure-html/fig-pcb-layout-output-1.png){#fig-pcb-layout}\n:::\n:::\n\n\n## Layout Rules {#sec-layout-rules}\n\n1. Place bypass capacitors (100nF) within 5mm of each IC power pin\n2. Route analog signals with minimum trace length; avoid crossing digital signals\n3. Use differential pairs for RX coil signals with matched length\n4. Keep TX and RX signal paths physically separated (>10mm)\n5. Provide shielding (copper pour) around sensitive analog circuits\n6. Use wide traces (>20 mil) for power distribution\n7. Connect analog and digital ground planes at a single star point near the ADC\n\n## Key Component Summary {#sec-components}\n\n| Component | Part Number | Function | Package | Rev |\n|-----------|-------------|----------|---------|-----|\n| DDS | AD9833BRMZ | Signal generator | MSOP-10 | A/B |\n| TX Driver | OPA454AIDDAR | Coil driver | SOIC-8 | A/B |\n| Preamp | AD8421BRZ | RX preamplifier | SOIC-8 | A/B |\n| Preamp (Alt) | INA188ID | Zero-drift preamp | SOIC-8 | B |\n| Inst Amp | INA128PAG4 | Gain stage | DIP-8 | A/B |\n| ADC | **AD7124-8BRUZ** | 24-bit integrated AFE | TQFP-32 | **B** |\n| ADC (Legacy) | ADS1256IDBR | 24-bit ADC | SSOP-28 | A |\n| Multiplexer | CD74HC4067M | 16-channel mux | SOIC-24 | A/B |\n| MCU | ESP32-WROOM-32 | Controller | Module | A/B |\n| V-Reference | REF5025AIDGKR | 2.5V reference | SOIC-8 | A/B |\n| LDO | AMS1117-3.3 | 3.3V regulator | SOT-223 | A/B |\n| Connector | **Weipu SP29-26** | IP68 hub connector | Circular | **B** |\n| Connector (Legacy) | DB25 | Hub connector | D-Sub | A |\n\n: Key IC Components (Rev B highlighted in bold). {#tbl-components}\n\n## Connector Pinouts (Probe-to-Zone) {#sec-pinouts}\n\n| Pin | Signal | Description |\n|-----|--------|-------------|\n| 1 | TX+ | To probe TX coil |\n| 2 | TX- | Return path |\n| 3 | RX+ | Differential RX |\n| 4 | RX- | Differential RX return |\n| 5 | Guard | Analog ground |\n| 6 | Ring A | Upper ERT electrode |\n| 7 | Ring B | Mid ERT electrode |\n| 8 | Ring C | Deep electrode |\n| 9 | ID Sense | Auto-ID resistor |\n| 10-11 | Spare | Reserved |\n| 12 | Shield | Cable shield clamp |\n\n: 12-pin Probe Connector Pinout. {#tbl-pinout}\n\n## Firmware Status {#sec-firmware-status}\n\n::: {.callout-note}\n## Firmware Development - Phase 2\n\nThe hardware system documented in this whitepaper requires MCU firmware to operate. Firmware development is explicitly **Phase 2** of the project, separate from the hardware design presented here.\n\n**Current Status:**\n\n- Hardware is designed for ESP32-WROOM-32 MCU\n- No firmware repository is published yet\n- Planned firmware features: DDS control, ADC sampling, lock-in detection, USB data logging\n\n**Planned Repository:** `github.com/hirt-project/hirt-firmware` (future)\n\nBuilders can test hardware subsystems (coils, ERT source, ADC) using bench equipment before firmware is available. See Section 18 for the software development roadmap.\n:::\n\n## Safety Considerations {#sec-safety}\n\n::: {.callout-warning}\n## ELECTRICAL SAFETY\n\n- Maximum output current limited to 5 mA by design\n- Compliance voltage restricted to +/-12V (safe for soil contact)\n- Include 10 mA fast-blow fuse on ERT output\n- Use opto-isolated relay control for polarity switching\n- Ensure proper earth ground connection for safety\n:::\n\n## Troubleshooting Guide {#sec-elec-troubleshooting}\n\n| Symptom | Likely Cause | Solution |\n|---------|--------------|----------|\n| No TX output | DDS not initialized | Check SPI connection, verify clock |\n| Weak RX signal | Gain too low | Verify R~G~ resistor, check amplifier rails |\n| Noisy readings | Ground loops | Implement star grounding, shield cables |\n| No ERT current | Open circuit | Check electrode contact, verify relay state |\n| Current drift | Reference unstable | Verify Vref output, add bypass caps |\n| ADC errors | SPI timing | Reduce SPI clock speed, check DRDY timing |\n\n: Common Issues and Solutions. {#tbl-troubleshooting}\n\n## Interconnect Modernization {#sec-interconnect}\n\nThe Rev B design replaces the legacy DB25 connectors with **Weipu SP29 (26-pin)** IP68-rated circular connectors. This addresses field reliability issues with non-waterproof D-Sub interfaces.\n\n### Weipu SP29 Specifications\n\n| Parameter | Specification |\n|-----------|---------------|\n| Pin Count | 26 pins (matches DB25 + 1 spare) |\n| IP Rating | **IP68** (waterproof, dust-tight) |\n| Coupling | Threaded (vibration-resistant) |\n| Panel Cutout | 29 mm |\n| Current Rating | 5 A per contact |\n| Shell Material | Nylon66 (rugged, cost-effective) |\n| Termination | Solder |\n\n: Weipu SP29 connector specifications. {#tbl-sp29-specs}\n\n**Migration Note:** The SP29's 26-pin configuration directly accommodates all 25 DB25 signals with one spare pin for future expansion. The threaded coupling provides a secure, watertight seal superior to the DB25's thumbscrew retention.\n\n### Alternative: CNLINKO LP-24\n\nFor applications requiring faster connection/disconnection, the CNLINKO LP-24 with snap-lock mechanism is acceptable but provides only 24 pins (requires reducing conductor count by one).\n\n## Electronics Modernization Roadmap {#sec-modernization}\n\nThe Rev B design already incorporates several key component upgrades: the AD8421 preamplifier and AD7124-8 integrated AFE replace legacy discrete solutions, and the Weipu SP29 connector provides IP68 environmental protection. Our ongoing component research identifies additional optimization opportunities for future board revisions.\n\nWe tracked electronics modernization opportunities through systematic component research focused on power efficiency, footprint reduction, and second-source availability. The Rev B design already benefits from the AD8421's 3 nV/rtHz noise floor and the AD7124-8's integrated AFE architecture. The following table summarizes additional upgrades under consideration:\n\n| Component | Current (Rev B) | Recommended Upgrade | Benefit | Status |\n|-----------|----------------|---------------------|---------|--------|\n| **DDS** | AD9833 (MSOP-10) | **AD9837** (LFCSP 3x3mm) | 33% power reduction (8.5 mW vs 12.65 mW), smaller footprint | **(Modeled)** |\n| **TX Driver** | OPA2186 | Already optimized | 89% power vs OPA2277 (90 µA vs 800 µA) | **(Modeled)** |\n| **Connector** | Weipu SP29 | Already upgraded | IP68 rating, 26-pin, rugged | Implemented |\n| **ADC** | AD7124-8 | ADS1261 (TI alternative) | Second source, 0.34 µV RMS noise, comparable specs | **(Modeled)** |\n\n: Electronics modernization summary. Rev B incorporates AD8421 and AD7124-8; additional upgrades are under evaluation. {#tbl-modernization}\n\n**DDS Upgrade Path: AD9837.** The AD9837 is a pin-compatible upgrade to the AD9833, offering identical SPI control and frequency generation capabilities in a smaller LFCSP-16 package (3x3 mm vs MSOP-10 footprint). The power reduction from 12.65 mW to 8.5 mW may extend battery life in multi-channel deployments. We classify this as a low-risk enhancement suitable for future PCB spins.\n\n**ADC Second Source: ADS1261.** While the AD7124-8 remains our primary recommendation, the Texas Instruments ADS1261 provides comparable performance (0.34 µV RMS noise, 24-bit resolution, integrated PGA) within the TI ecosystem. This offers supply chain diversity and may be preferable for teams already standardized on TI components.\n\n::: {.callout-tip}\n## Pre-Order Component Strategy\n\nElectronic component markets are volatile. Tariff announcements in late 2025 suggest potential 20-30% price increases for imports in 2026. For builders planning multi-unit production, we recommend pre-ordering AD8421, AD7124-8, and AD9833/AD9837 stock now to lock in current pricing. Store ICs in sealed moisture-barrier bags with desiccant.\n:::\n\n## Legacy Components (Deprecated) {#sec-legacy-components}\n\nThe following components are documented for historical builds and maintenance of Rev A systems. **New builds should use Rev B components.**\n\n### ADS1256 (Legacy ADC)\n\n| Parameter | ADS1256 Specification |\n|-----------|----------------------|\n| Resolution | 24 bits |\n| Sample Rate | 30 kSPS maximum |\n| Noise | 0.6 µV RMS (at 100 SPS) |\n| Interface | SPI |\n| Internal PGA | 1, 2, 4, 8, 16, 32, 64x |\n| Input Channels | 8 single-ended or 4 differential |\n| Power | ~36 mW typical |\n\n: ADS1256 ADC Specifications (Legacy - Not Recommended for New Builds). {#tbl-adc-legacy}\n\n::: {.callout-warning}\n## Legacy Component - Not Maintained\n\nThe ADS1256 requires significant external circuitry (reference buffers, input drivers) to achieve datasheet performance, increasing PCB footprint and power budget. New builds should use the AD7124-8, which integrates these functions and offers superior power efficiency.\n:::\n\n### DB25 Connector (Legacy Interconnect)\n\nThe DB25 connector is not waterproof and is prone to corrosion in field environments. Rev B replaces this with the Weipu SP29 IP68 connector. Existing systems can continue using DB25 but should add environmental protection (conformal coating, protective caps) for field use.\n\n## References {#sec-electronics-references}\n\n1. Analog Devices. AD9833 Programmable Waveform Generator Data Sheet. Rev. F, 2019. [Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/AD9833.pdf)\n\n2. Texas Instruments. OPA454 High-Voltage, High-Current Operational Amplifier. SBOS328D, 2018. [Datasheet](https://www.ti.com/lit/ds/symlink/opa454.pdf)\n\n3. Analog Devices. AD620 Low Cost, Low Power Instrumentation Amplifier. Rev. H, 2011. [Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/AD620.pdf)\n\n4. Texas Instruments. INA128 Precision, Low Power Instrumentation Amplifiers. SBOS051B, 2005. [Datasheet](https://www.ti.com/lit/ds/symlink/ina128.pdf)\n\n5. Texas Instruments. ADS1256 Very Low Noise, 24-Bit Analog-to-Digital Converter. SBAS288K, 2013. [Datasheet](https://www.ti.com/lit/ds/symlink/ads1256.pdf)\n\n6. Horowitz, P. and Hill, W. (2015). *The Art of Electronics*, 3rd Edition. Cambridge University Press. Chapter 5: Precision Circuits. [DOI: 10.1017/CBO9781139644204](https://doi.org/10.1017/CBO9781139644204)\n\n7. Ott, H.W. (2009). *Electromagnetic Compatibility Engineering*. Wiley. Chapter 3: Grounding. [DOI: 10.1002/9780470508510](https://doi.org/10.1002/9780470508510)\n\n",
    "supporting": [
      "electronics_files"
    ],
    "filters": [],
    "includes": {}
  }
}